theme: jekyll-theme-minimal
title:            Emma Reich
description: Welcome!

</style>
<div align="center">
<img src="https://egreich.github.io/public/Emmanewt.jpg" alt="A picture of me (Emma) at Pepperwood Preserve, taking a break in between soil moisture measurements to hold a newt" class="circular--square"/>
</div>
