theme: jekyll-theme-minimal
title:            Emma Reich
description: PhD Student in Ecological and Environmental Informatics <br><br><a href="/aboutme">About Me</a> <br><br><a href="/REICH CV.pdf">CV</a> <br><br><a href="/anotherpage">Thoughts on Science</a>
