theme: jekyll-theme-minimal
title:            Emma Reich
description: Welcome!

avatar: <img src="https://egreich.github.io/public/Emmanewt.jpg" alt="A picture of me (Sruthi) at a restaurant, taken by my friend Catherine Han!" class="circular--square"/>
